services:
  - type: web
    name: sol-gen-idea-pro
    env: node
    region: frankfurt
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: NFT_STORAGE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
